home_assistant:
  container_name: home_assistant
  build: .
  tty: true
  ports:
    - 8123:8123
  volumes:
    - .:/config
    - ./google2ef72f799271da64.html:/usr/local/lib/python3.4/dist-packages/homeassistant/components/frontend/www_static/google2ef72f799271da64.html
    - /home/josh/home-assistant-lets-encrypt/etc/letsencrypt:/etc/letsencrypt:ro
