home_assistant:
  container_name: home_assistant
  build: .
  net: host
  ports:
    - 8123:8123
  volumes:
    - .:/config
    - /etc/localtime:/etc/localtime:ro
    - /home/josh/home-assistant-lets-encrypt/etc/letsencrypt/live:/etc/ssl/certs
