- platform: template
  sensors:
    garage_door_1_status: 
        friendly_name: "Main Garage Door Status"
        value_template: '{% if is_state("switch.garagebasestation_2_3", "on") -%}Open{% else -%}Closed{%- endif %}'
        icon_template: '{% if is_state("switch.garagebasestation_2_3", "on") -%}mdi:garage-open{% else -%}mdi:garage{%- endif %}'
    sunrise:
        friendly_name: Sunrise
        value_template: '{{ ((as_timestamp(states.sun.sun.attributes.next_rising)) | timestamp_local)[11:16] }}'
    sunset:
        friendly_name: Sunset
        value_template: '{{ ((as_timestamp(states.sun.sun.attributes.next_setting)) | timestamp_local)[11:16] }}'