homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 76
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Pacific/Auckland
  customize: !include customizations.yaml
  customize_glob: !include_dir_merge_named customizations   

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  ssl_certificate: !secret ssl_certificate_path
  ssl_key: !secret ssl_key_path

# Checks for available updates
updater:

logger:
  logs:
    homeassistant.components.mysensors: debug
    homeassistant.components.climate.mysensors: debug
    homeassistant.sensor.mysensors: debug

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# MQTT config
mqtt:
  broker: !secret mqtt_host
  keepalive: 60
  client_id: "home-assistant"

# Track the sun
sun:

group: !include_dir_merge_named groups/
camera: !include_dir_list cameras/
script: !include_dir_merge_named scripts/
sensor: !include_dir_merge_list sensors/
automation: !include_dir_merge_list automation/

device_tracker:
  - platform: ddwrt
    host: !secret router_host
    username: !secret router_username
    password: !secret router_password

notify:
  - platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

mysensors:
  gateways:
    - device: mqtt
      persistence_file: '/config/mysensors.json'
      topic_in_prefix: 'mysensors-out'
      topic_out_prefix: 'mysensors-in'
  optimistic: true
  retain: true
  debug: true
  persistence: true

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password


climate:
  - platform: mysensors
    name: studyclimate_3_2
# Text to speech
tts:
  platform: google
